---
title: "Programming Practice: Lab 2"
execute:
  enabled: true
  echo: true
  cache: true
format:
  html:
    code-fold: false
jupyter: python3
diagram:
  cache: true
  cache-dir: ./cache
  engine:
    tikz:
      execpath: lualatex
filters:
  - diagram
---

# Git Fundamentals

1. Install Git for Windows.
2. Run `Git Bash`.
3. Create a test directory: `mkdir test`.
4. Navigate to test directory: `cd test`.
5. Create a test file: `echo "test contents" > test.txt`.
6. Initialize a Git repo: `git init`.
7. Check Git repo status: `git status`.
8. Add the test file: `git add test.txt`.
9. Commit the test file: `git commit -m "Commit message"`
  - Git will complain that it doesn't know who you are. Update your name and email per it's instructions.
10. Navigate to GitHub and create your account and repository.
11. Copy repository URL and set it in your local repo via `git remote add origin <GITHUB_REPO_URL>`.
12. Push your local changes to remote repo: `git push -u origin master`.
  - Note that `-u` option is only needed the first time you're doing the push in any local branch.


# Recommended reading: 

- 

# Exercises
**Task 1.** Create a repo for BlockProcessor task  and push it to GitHub.
