---
title: "Programming Practice: Lab 3"
execute:
  enabled: true
  echo: true
  cache: true
format:
  html:
    code-fold: false
jupyter: python3
diagram:
  cache: true
  cache-dir: ./cache
  engine:
    tikz:
      execpath: lualatex
filters:
  - diagram
---

# Python Regular Expressions

 Required reading: 

- Official [Python package documentation](https://docs.python.org/3/howto/regex.html).
- [Regex cheatsheet](https://www.debuggex.com/cheatsheet/regex/python)
- [Cheatsheet with examples](https://images.datacamp.com/image/upload/v1665049611/Marketing/Blog/Regular_Expressions_Cheat_Sheet.pdf)

# Exercises
**Task 1.** Write regexes that:

- remove all special (non-alphanumeric) characters from a string.
- match a word that contains a given character (e.g. "y").
- match a word that is $n$ characters long.
- match a word that begins with "a" OR "b" and ends with "s".

**Task 2.** Write a program that will 

- collect all monetary amounts from a given text.

   Example: "first amount is $123.45, second amount is $400" -> `[123.45, 400]`.

- convert these to float numbers
- and sum them

**Task 3.** Write a program that will cleanup Python source code by:

- removing source code comments from Python code.
- removing blank lines (hint: use `\r`, `\n` special characters)

**Task 4.** Write a program that will convert dates in "yyyy-mm-dd"\ format to "dd-mm-yyyy"\ format.

Example: `2024-02-11 -> 11-02-2024`.
